parameters:
    phumbor.url.builder_factory.class: Thumbor\Url\BuilderFactory
    phumbor.url.transformer.class: Jb\Bundle\PhumborBundle\Transformer\BaseTransformer
    phumbor.twig.extension.class: Jb\Bundle\PhumborBundle\Twig\PhumborExtension

services:
    Thumbor\Url\BuilderFactory:
        class: '%phumbor.url.builder_factory.class%'
        arguments:
            - '%phumbor.server.url%'
            - '%phumbor.secret%'

    Jb\Bundle\PhumborBundle\Transformer\BaseTransformer:
        class: '%phumbor.url.transformer.class%'
        arguments:
            - '@Thumbor\Url\BuilderFactory'
            - '%phumbor.transformations%'

    Jb\Bundle\PhumborBundle\Twig\PhumborExtension:
        class: '%phumbor.twig.extension.class%'
        arguments:
            - '@Jb\Bundle\PhumborBundle\Transformer\BaseTransformer'
        tags:
            - { name: twig.extension }

    # Service aliases for BC:
    phumbor.url.builder_factory:
        alias: Thumbor\Url\BuilderFactory

    phumbor.url.transformer:
        alias: Jb\Bundle\PhumborBundle\Transformer\BaseTransformer

    phumbor.twig.extension:
        alias: Jb\Bundle\PhumborBundle\Twig\PhumborExtension
